# fly.toml app configuration file generated for stock-app-tr on 2024-08-21T10:25:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-app-tr'
primary_region = 'arn'

[env]
  PORT = '8080'

[processes]
  app = 'node index.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
